// 📝 Auto-generated by E2E-Autogen
// 🔧 Generated from: TC-1.1

import { test } from "@playwright/test";

test.skip("[TC-1.1] 유저 리스트", async ({ page }) => {
  await test.step.skip("[TC-1.1.1] 메인화면 로드 -> 제목(User Management)이 표시되어야 한다", async () => {
      // 📍 UI Path: 홈

      // 🎬 When: 메인화면 로드
    
      // ✅ Then: 제목(User Management)이 표시되어야 한다

    });

  await test.step.skip("[TC-1.1.2] Username, Email 인풋필드가 표시되어야 한다", async () => {
      
          
      // ✅ Then: Username, Email 인풋필드가 표시되어야 한다

    });

  await test.step.skip("[TC-1.1.3] 유저가 4명 표시되어야 한다", async () => {
      
          
      // ✅ Then: 유저가 4명 표시되어야 한다

    });
});